version: "3"
services:
  ##########################################################
  #                      SABNZBD                           #
  ##########################################################

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${NAS_PUID}
      - PGID=${NAS_PGID}
      - UMASK=${NAS_UMASK}
      - TZ=${TZ}
    volumes:
      - ${Docker_Mount}/sabnzbd/config:/config
      - ${Docker_Mount}/sabnzbd/downloads:/downloads #optional
      - ${Docker_Mount}/sabnzbd/incomplete-downloads:/incomplete-downloads #optional
      - ${Docker_Mount}/sabnzbd/downloads/books:/downloads/books
    ports:
      - ${sabnzbd_PORT}:8080
    restart: unless-stopped
